//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasUnitarias.wcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Configuracion")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PruebasUnitarias.wcf.OFICINA_IP> List_OFICINA_IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PruebasUnitarias.wcf.OFICINA_IP OFICINA_IPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PruebasUnitarias.wcf.OFICINA_IP> List_OFICINA_IP {
            get {
                return this.List_OFICINA_IPField;
            }
            set {
                if ((object.ReferenceEquals(this.List_OFICINA_IPField, value) != true)) {
                    this.List_OFICINA_IPField = value;
                    this.RaisePropertyChanged("List_OFICINA_IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PruebasUnitarias.wcf.OFICINA_IP OFICINA_IP {
            get {
                return this.OFICINA_IPField;
            }
            set {
                if ((object.ReferenceEquals(this.OFICINA_IPField, value) != true)) {
                    this.OFICINA_IPField = value;
                    this.RaisePropertyChanged("OFICINA_IP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OFICINA_IP", Namespace="http://schemas.datacontract.org/2004/07/Entidades.bdgeneral")]
    [System.SerializableAttribute()]
    public partial class OFICINA_IP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENVIO_POSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ip_rango_finalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ip_rango_inicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ip_redField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oficinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENVIO_POS {
            get {
                return this.ENVIO_POSField;
            }
            set {
                if ((object.ReferenceEquals(this.ENVIO_POSField, value) != true)) {
                    this.ENVIO_POSField = value;
                    this.RaisePropertyChanged("ENVIO_POS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ip_rango_final {
            get {
                return this.ip_rango_finalField;
            }
            set {
                if ((this.ip_rango_finalField.Equals(value) != true)) {
                    this.ip_rango_finalField = value;
                    this.RaisePropertyChanged("ip_rango_final");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ip_rango_inicial {
            get {
                return this.ip_rango_inicialField;
            }
            set {
                if ((this.ip_rango_inicialField.Equals(value) != true)) {
                    this.ip_rango_inicialField = value;
                    this.RaisePropertyChanged("ip_rango_inicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip_red {
            get {
                return this.ip_redField;
            }
            set {
                if ((object.ReferenceEquals(this.ip_redField, value) != true)) {
                    this.ip_redField = value;
                    this.RaisePropertyChanged("ip_red");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oficina {
            get {
                return this.oficinaField;
            }
            set {
                if ((object.ReferenceEquals(this.oficinaField, value) != true)) {
                    this.oficinaField = value;
                    this.RaisePropertyChanged("oficina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Configuracion")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PruebasUnitarias.wcf.Log> List_LogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PruebasUnitarias.wcf.OFICINA_IP> List_OFICINA_IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PruebasUnitarias.wcf.Log LogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PruebasUnitarias.wcf.OFICINA_IP OFICINA_IPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PruebasUnitarias.wcf.Log> List_Log {
            get {
                return this.List_LogField;
            }
            set {
                if ((object.ReferenceEquals(this.List_LogField, value) != true)) {
                    this.List_LogField = value;
                    this.RaisePropertyChanged("List_Log");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PruebasUnitarias.wcf.OFICINA_IP> List_OFICINA_IP {
            get {
                return this.List_OFICINA_IPField;
            }
            set {
                if ((object.ReferenceEquals(this.List_OFICINA_IPField, value) != true)) {
                    this.List_OFICINA_IPField = value;
                    this.RaisePropertyChanged("List_OFICINA_IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PruebasUnitarias.wcf.Log Log {
            get {
                return this.LogField;
            }
            set {
                if ((object.ReferenceEquals(this.LogField, value) != true)) {
                    this.LogField = value;
                    this.RaisePropertyChanged("Log");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PruebasUnitarias.wcf.OFICINA_IP OFICINA_IP {
            get {
                return this.OFICINA_IPField;
            }
            set {
                if ((object.ReferenceEquals(this.OFICINA_IPField, value) != true)) {
                    this.OFICINA_IPField = value;
                    this.RaisePropertyChanged("OFICINA_IP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Log", Namespace="http://schemas.datacontract.org/2004/07/Configuracion.Librerias")]
    [System.SerializableAttribute()]
    public partial class Log : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cls_Cabecera", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class cls_Cabecera : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PruebasUnitarias.wcf.articulos> articulosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string base64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ctcostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_planField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string origenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PruebasUnitarias.wcf.articulos> articulos {
            get {
                return this.articulosField;
            }
            set {
                if ((object.ReferenceEquals(this.articulosField, value) != true)) {
                    this.articulosField = value;
                    this.RaisePropertyChanged("articulos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string base64 {
            get {
                return this.base64Field;
            }
            set {
                if ((object.ReferenceEquals(this.base64Field, value) != true)) {
                    this.base64Field = value;
                    this.RaisePropertyChanged("base64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string compania {
            get {
                return this.companiaField;
            }
            set {
                if ((object.ReferenceEquals(this.companiaField, value) != true)) {
                    this.companiaField = value;
                    this.RaisePropertyChanged("compania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ctcosto {
            get {
                return this.ctcostoField;
            }
            set {
                if ((object.ReferenceEquals(this.ctcostoField, value) != true)) {
                    this.ctcostoField = value;
                    this.RaisePropertyChanged("ctcosto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_plan {
            get {
                return this.id_planField;
            }
            set {
                if ((this.id_planField.Equals(value) != true)) {
                    this.id_planField = value;
                    this.RaisePropertyChanged("id_plan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oficina {
            get {
                return this.oficinaField;
            }
            set {
                if ((object.ReferenceEquals(this.oficinaField, value) != true)) {
                    this.oficinaField = value;
                    this.RaisePropertyChanged("oficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string origen {
            get {
                return this.origenField;
            }
            set {
                if ((object.ReferenceEquals(this.origenField, value) != true)) {
                    this.origenField = value;
                    this.RaisePropertyChanged("origen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sucursal {
            get {
                return this.sucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.sucursalField, value) != true)) {
                    this.sucursalField = value;
                    this.RaisePropertyChanged("sucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="articulos", Namespace="http://schemas.datacontract.org/2004/07/Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class articulos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string barraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool coincideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int valorconversionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string barra {
            get {
                return this.barraField;
            }
            set {
                if ((object.ReferenceEquals(this.barraField, value) != true)) {
                    this.barraField = value;
                    this.RaisePropertyChanged("barra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool coincide {
            get {
                return this.coincideField;
            }
            set {
                if ((this.coincideField.Equals(value) != true)) {
                    this.coincideField = value;
                    this.RaisePropertyChanged("coincide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ingreso {
            get {
                return this.ingresoField;
            }
            set {
                if ((this.ingresoField.Equals(value) != true)) {
                    this.ingresoField = value;
                    this.RaisePropertyChanged("ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int valorconversion {
            get {
                return this.valorconversionField;
            }
            set {
                if ((this.valorconversionField.Equals(value) != true)) {
                    this.valorconversionField = value;
                    this.RaisePropertyChanged("valorconversion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Traspaso", Namespace="http://schemas.datacontract.org/2004/07/Configuracion.Models")]
    [System.SerializableAttribute()]
    public partial class Traspaso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PruebasUnitarias.wcf.DetalleTraspaso> articulosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bodegaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaTraspasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fundaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string traspasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioFarmaciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PruebasUnitarias.wcf.DetalleTraspaso> articulos {
            get {
                return this.articulosField;
            }
            set {
                if ((object.ReferenceEquals(this.articulosField, value) != true)) {
                    this.articulosField = value;
                    this.RaisePropertyChanged("articulos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bodega {
            get {
                return this.bodegaField;
            }
            set {
                if ((object.ReferenceEquals(this.bodegaField, value) != true)) {
                    this.bodegaField = value;
                    this.RaisePropertyChanged("bodega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int caja {
            get {
                return this.cajaField;
            }
            set {
                if ((this.cajaField.Equals(value) != true)) {
                    this.cajaField = value;
                    this.RaisePropertyChanged("caja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaTraspaso {
            get {
                return this.fechaTraspasoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaTraspasoField, value) != true)) {
                    this.fechaTraspasoField = value;
                    this.RaisePropertyChanged("fechaTraspaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int funda {
            get {
                return this.fundaField;
            }
            set {
                if ((this.fundaField.Equals(value) != true)) {
                    this.fundaField = value;
                    this.RaisePropertyChanged("funda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int paca {
            get {
                return this.pacaField;
            }
            set {
                if ((this.pacaField.Equals(value) != true)) {
                    this.pacaField = value;
                    this.RaisePropertyChanged("paca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string traspaso {
            get {
                return this.traspasoField;
            }
            set {
                if ((object.ReferenceEquals(this.traspasoField, value) != true)) {
                    this.traspasoField = value;
                    this.RaisePropertyChanged("traspaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioFarmacia {
            get {
                return this.usuarioFarmaciaField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioFarmaciaField, value) != true)) {
                    this.usuarioFarmaciaField = value;
                    this.RaisePropertyChanged("usuarioFarmacia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleTraspaso", Namespace="http://schemas.datacontract.org/2004/07/Configuracion.Models")]
    [System.SerializableAttribute()]
    public partial class DetalleTraspaso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PruebasUnitarias.wcf.R_Barra> barrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int enteroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fraccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int masField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int menosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PruebasUnitarias.wcf.R_Barra> barras {
            get {
                return this.barrasField;
            }
            set {
                if ((object.ReferenceEquals(this.barrasField, value) != true)) {
                    this.barrasField = value;
                    this.RaisePropertyChanged("barras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int entero {
            get {
                return this.enteroField;
            }
            set {
                if ((this.enteroField.Equals(value) != true)) {
                    this.enteroField = value;
                    this.RaisePropertyChanged("entero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fraccion {
            get {
                return this.fraccionField;
            }
            set {
                if ((this.fraccionField.Equals(value) != true)) {
                    this.fraccionField = value;
                    this.RaisePropertyChanged("fraccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mas {
            get {
                return this.masField;
            }
            set {
                if ((this.masField.Equals(value) != true)) {
                    this.masField = value;
                    this.RaisePropertyChanged("mas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int menos {
            get {
                return this.menosField;
            }
            set {
                if ((this.menosField.Equals(value) != true)) {
                    this.menosField = value;
                    this.RaisePropertyChanged("menos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="R_Barra", Namespace="http://schemas.datacontract.org/2004/07/Configuracion.Models")]
    [System.SerializableAttribute()]
    public partial class R_Barra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Temporal", Namespace="http://schemas.datacontract.org/2004/07/Configuracion.Models")]
    [System.SerializableAttribute()]
    public partial class Temporal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data2 {
            get {
                return this.data2Field;
            }
            set {
                if ((object.ReferenceEquals(this.data2Field, value) != true)) {
                    this.data2Field = value;
                    this.RaisePropertyChanged("data2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.identificadorField, value) != true)) {
                    this.identificadorField = value;
                    this.RaisePropertyChanged("identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cookie", Namespace="http://schemas.datacontract.org/2004/07/Configuracion.Models")]
    [System.SerializableAttribute()]
    public partial class Cookie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cookieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipDispositivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cookie {
            get {
                return this.cookieField;
            }
            set {
                if ((object.ReferenceEquals(this.cookieField, value) != true)) {
                    this.cookieField = value;
                    this.RaisePropertyChanged("cookie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ipDispositivo {
            get {
                return this.ipDispositivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ipDispositivoField, value) != true)) {
                    this.ipDispositivoField = value;
                    this.RaisePropertyChanged("ipDispositivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsu {
            get {
                return this.nombreUsuField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuField, value) != true)) {
                    this.nombreUsuField = value;
                    this.RaisePropertyChanged("nombreUsu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TraspasoModel", Namespace="http://schemas.datacontract.org/2004/07/Configuracion.Models")]
    [System.SerializableAttribute()]
    public partial class TraspasoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodegaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> CajasPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> CajasVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaTraspasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FundaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> FundasPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> FundasVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTraspasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> PacasPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> PacasVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioFarmaciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bodega {
            get {
                return this.BodegaField;
            }
            set {
                if ((object.ReferenceEquals(this.BodegaField, value) != true)) {
                    this.BodegaField = value;
                    this.RaisePropertyChanged("Bodega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Caja {
            get {
                return this.CajaField;
            }
            set {
                if ((this.CajaField.Equals(value) != true)) {
                    this.CajaField = value;
                    this.RaisePropertyChanged("Caja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> CajasP {
            get {
                return this.CajasPField;
            }
            set {
                if ((object.ReferenceEquals(this.CajasPField, value) != true)) {
                    this.CajasPField = value;
                    this.RaisePropertyChanged("CajasP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> CajasV {
            get {
                return this.CajasVField;
            }
            set {
                if ((object.ReferenceEquals(this.CajasVField, value) != true)) {
                    this.CajasVField = value;
                    this.RaisePropertyChanged("CajasV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Check {
            get {
                return this.CheckField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckField, value) != true)) {
                    this.CheckField = value;
                    this.RaisePropertyChanged("Check");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionEstado {
            get {
                return this.DescripcionEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionEstadoField, value) != true)) {
                    this.DescripcionEstadoField = value;
                    this.RaisePropertyChanged("DescripcionEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaTraspaso {
            get {
                return this.FechaTraspasoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaTraspasoField, value) != true)) {
                    this.FechaTraspasoField = value;
                    this.RaisePropertyChanged("FechaTraspaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Funda {
            get {
                return this.FundaField;
            }
            set {
                if ((this.FundaField.Equals(value) != true)) {
                    this.FundaField = value;
                    this.RaisePropertyChanged("Funda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> FundasP {
            get {
                return this.FundasPField;
            }
            set {
                if ((object.ReferenceEquals(this.FundasPField, value) != true)) {
                    this.FundasPField = value;
                    this.RaisePropertyChanged("FundasP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> FundasV {
            get {
                return this.FundasVField;
            }
            set {
                if ((object.ReferenceEquals(this.FundasVField, value) != true)) {
                    this.FundasVField = value;
                    this.RaisePropertyChanged("FundasV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTraspaso {
            get {
                return this.NumeroTraspasoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTraspasoField, value) != true)) {
                    this.NumeroTraspasoField = value;
                    this.RaisePropertyChanged("NumeroTraspaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Paca {
            get {
                return this.PacaField;
            }
            set {
                if ((this.PacaField.Equals(value) != true)) {
                    this.PacaField = value;
                    this.RaisePropertyChanged("Paca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> PacasP {
            get {
                return this.PacasPField;
            }
            set {
                if ((object.ReferenceEquals(this.PacasPField, value) != true)) {
                    this.PacasPField = value;
                    this.RaisePropertyChanged("PacasP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> PacasV {
            get {
                return this.PacasVField;
            }
            set {
                if ((object.ReferenceEquals(this.PacasVField, value) != true)) {
                    this.PacasVField = value;
                    this.RaisePropertyChanged("PacasV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioFarmacia {
            get {
                return this.UsuarioFarmaciaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioFarmaciaField, value) != true)) {
                    this.UsuarioFarmaciaField = value;
                    this.RaisePropertyChanged("UsuarioFarmacia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Test", ReplyAction="http://tempuri.org/IService1/TestResponse")]
        System.IO.Stream Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Test", ReplyAction="http://tempuri.org/IService1/TestResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ips", ReplyAction="http://tempuri.org/IService1/IpsResponse")]
        PruebasUnitarias.wcf.Response Ips(PruebasUnitarias.wcf.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ips", ReplyAction="http://tempuri.org/IService1/IpsResponse")]
        System.Threading.Tasks.Task<PruebasUnitarias.wcf.Response> IpsAsync(PruebasUnitarias.wcf.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AutentificarUsuario", ReplyAction="http://tempuri.org/IService1/AutentificarUsuarioResponse")]
        System.IO.Stream AutentificarUsuario(string usuario, string contrasena, string ipMovil, string ipMovil2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AutentificarUsuario", ReplyAction="http://tempuri.org/IService1/AutentificarUsuarioResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> AutentificarUsuarioAsync(string usuario, string contrasena, string ipMovil, string ipMovil2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoPlanificaciones", ReplyAction="http://tempuri.org/IService1/ListadoPlanificacionesResponse")]
        System.IO.Stream ListadoPlanificaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoPlanificaciones", ReplyAction="http://tempuri.org/IService1/ListadoPlanificacionesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ListadoPlanificacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoArticulosPlanificacion", ReplyAction="http://tempuri.org/IService1/ListadoArticulosPlanificacionResponse")]
        System.IO.Stream ListadoArticulosPlanificacion(string id_plan, string origen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoArticulosPlanificacion", ReplyAction="http://tempuri.org/IService1/ListadoArticulosPlanificacionResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ListadoArticulosPlanificacionAsync(string id_plan, string origen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RestringirArticulosContar", ReplyAction="http://tempuri.org/IService1/RestringirArticulosContarResponse")]
        System.IO.Stream RestringirArticulosContar(string id_plan, string origen, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RestringirArticulosContar", ReplyAction="http://tempuri.org/IService1/RestringirArticulosContarResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> RestringirArticulosContarAsync(string id_plan, string origen, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPlanificacionaContar", ReplyAction="http://tempuri.org/IService1/ActualizarPlanificacionaContarResponse")]
        System.IO.Stream ActualizarPlanificacionaContar(string id_plan, string origen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPlanificacionaContar", ReplyAction="http://tempuri.org/IService1/ActualizarPlanificacionaContarResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ActualizarPlanificacionaContarAsync(string id_plan, string origen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubirConteoInventario", ReplyAction="http://tempuri.org/IService1/SubirConteoInventarioResponse")]
        System.IO.Stream SubirConteoInventario(PruebasUnitarias.wcf.cls_Cabecera conteoInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubirConteoInventario", ReplyAction="http://tempuri.org/IService1/SubirConteoInventarioResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> SubirConteoInventarioAsync(PruebasUnitarias.wcf.cls_Cabecera conteoInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraspasosFarmacia", ReplyAction="http://tempuri.org/IService1/TraspasosFarmaciaResponse")]
        System.IO.Stream TraspasosFarmacia(string id_bodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraspasosFarmacia", ReplyAction="http://tempuri.org/IService1/TraspasosFarmaciaResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> TraspasosFarmaciaAsync(string id_bodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DetalleTraspasos", ReplyAction="http://tempuri.org/IService1/DetalleTraspasosResponse")]
        System.IO.Stream DetalleTraspasos(string traspaso, string bodegaOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DetalleTraspasos", ReplyAction="http://tempuri.org/IService1/DetalleTraspasosResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DetalleTraspasosAsync(string traspaso, string bodegaOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarArticuloTraspaso", ReplyAction="http://tempuri.org/IService1/BuscarArticuloTraspasoResponse")]
        System.IO.Stream BuscarArticuloTraspaso(string id_bodega, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarArticuloTraspaso", ReplyAction="http://tempuri.org/IService1/BuscarArticuloTraspasoResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> BuscarArticuloTraspasoAsync(string id_bodega, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarTraspasoKardexFarmacia", ReplyAction="http://tempuri.org/IService1/VerificarTraspasoKardexFarmaciaResponse")]
        System.IO.Stream VerificarTraspasoKardexFarmacia(string id_bodega, string traspaso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarTraspasoKardexFarmacia", ReplyAction="http://tempuri.org/IService1/VerificarTraspasoKardexFarmaciaResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> VerificarTraspasoKardexFarmaciaAsync(string id_bodega, string traspaso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerarKardex", ReplyAction="http://tempuri.org/IService1/GenerarKardexResponse")]
        System.IO.Stream GenerarKardex(PruebasUnitarias.wcf.Traspaso traspaso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerarKardex", ReplyAction="http://tempuri.org/IService1/GenerarKardexResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GenerarKardexAsync(PruebasUnitarias.wcf.Traspaso traspaso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ImagenArticulo", ReplyAction="http://tempuri.org/IService1/ImagenArticuloResponse")]
        System.IO.Stream ImagenArticulo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ImagenArticulo", ReplyAction="http://tempuri.org/IService1/ImagenArticuloResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ImagenArticuloAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarTemporal", ReplyAction="http://tempuri.org/IService1/GuardarTemporalResponse")]
        System.IO.Stream GuardarTemporal(PruebasUnitarias.wcf.Temporal temporal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarTemporal", ReplyAction="http://tempuri.org/IService1/GuardarTemporalResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GuardarTemporalAsync(PruebasUnitarias.wcf.Temporal temporal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarTemporal", ReplyAction="http://tempuri.org/IService1/RecuperarTemporalResponse")]
        System.IO.Stream RecuperarTemporal(string identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarTemporal", ReplyAction="http://tempuri.org/IService1/RecuperarTemporalResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> RecuperarTemporalAsync(string identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarTemporal", ReplyAction="http://tempuri.org/IService1/EliminarTemporalResponse")]
        System.IO.Stream EliminarTemporal(string identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarTemporal", ReplyAction="http://tempuri.org/IService1/EliminarTemporalResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> EliminarTemporalAsync(string identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Cookie", ReplyAction="http://tempuri.org/IService1/CookieResponse")]
        System.IO.Stream Cookie([System.ServiceModel.MessageParameterAttribute(Name="cookie")] PruebasUnitarias.wcf.Cookie cookie1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Cookie", ReplyAction="http://tempuri.org/IService1/CookieResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> CookieAsync(PruebasUnitarias.wcf.Cookie cookie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Servidor", ReplyAction="http://tempuri.org/IService1/ServidorResponse")]
        System.IO.Stream Servidor(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Servidor", ReplyAction="http://tempuri.org/IService1/ServidorResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ServidorAsync(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarFactura", ReplyAction="http://tempuri.org/IService1/VerificarFacturaResponse")]
        System.IO.Stream VerificarFactura(string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarFactura", ReplyAction="http://tempuri.org/IService1/VerificarFacturaResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> VerificarFacturaAsync(string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Digitalizacion", ReplyAction="http://tempuri.org/IService1/DigitalizacionResponse")]
        System.IO.Stream Digitalizacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Digitalizacion", ReplyAction="http://tempuri.org/IService1/DigitalizacionResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DigitalizacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificacionCajas", ReplyAction="http://tempuri.org/IService1/VerificacionCajasResponse")]
        System.IO.Stream VerificacionCajas(string bodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificacionCajas", ReplyAction="http://tempuri.org/IService1/VerificacionCajasResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> VerificacionCajasAsync(string bodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarPendientesVerificacion", ReplyAction="http://tempuri.org/IService1/GuardarPendientesVerificacionResponse")]
        System.IO.Stream GuardarPendientesVerificacion(System.Collections.Generic.List<PruebasUnitarias.wcf.TraspasoModel> traspasosModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarPendientesVerificacion", ReplyAction="http://tempuri.org/IService1/GuardarPendientesVerificacionResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GuardarPendientesVerificacionAsync(System.Collections.Generic.List<PruebasUnitarias.wcf.TraspasoModel> traspasosModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PruebasUnitarias.wcf.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PruebasUnitarias.wcf.IService1>, PruebasUnitarias.wcf.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> TestAsync() {
            return base.Channel.TestAsync();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public PruebasUnitarias.wcf.Response Ips(PruebasUnitarias.wcf.Request request) {
            return base.Channel.Ips(request);
        }
        
        public System.Threading.Tasks.Task<PruebasUnitarias.wcf.Response> IpsAsync(PruebasUnitarias.wcf.Request request) {
            return base.Channel.IpsAsync(request);
        }
        
        public System.IO.Stream AutentificarUsuario(string usuario, string contrasena, string ipMovil, string ipMovil2) {
            return base.Channel.AutentificarUsuario(usuario, contrasena, ipMovil, ipMovil2);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> AutentificarUsuarioAsync(string usuario, string contrasena, string ipMovil, string ipMovil2) {
            return base.Channel.AutentificarUsuarioAsync(usuario, contrasena, ipMovil, ipMovil2);
        }
        
        public System.IO.Stream ListadoPlanificaciones() {
            return base.Channel.ListadoPlanificaciones();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ListadoPlanificacionesAsync() {
            return base.Channel.ListadoPlanificacionesAsync();
        }
        
        public System.IO.Stream ListadoArticulosPlanificacion(string id_plan, string origen) {
            return base.Channel.ListadoArticulosPlanificacion(id_plan, origen);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ListadoArticulosPlanificacionAsync(string id_plan, string origen) {
            return base.Channel.ListadoArticulosPlanificacionAsync(id_plan, origen);
        }
        
        public System.IO.Stream RestringirArticulosContar(string id_plan, string origen, string usuario) {
            return base.Channel.RestringirArticulosContar(id_plan, origen, usuario);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> RestringirArticulosContarAsync(string id_plan, string origen, string usuario) {
            return base.Channel.RestringirArticulosContarAsync(id_plan, origen, usuario);
        }
        
        public System.IO.Stream ActualizarPlanificacionaContar(string id_plan, string origen) {
            return base.Channel.ActualizarPlanificacionaContar(id_plan, origen);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ActualizarPlanificacionaContarAsync(string id_plan, string origen) {
            return base.Channel.ActualizarPlanificacionaContarAsync(id_plan, origen);
        }
        
        public System.IO.Stream SubirConteoInventario(PruebasUnitarias.wcf.cls_Cabecera conteoInventario) {
            return base.Channel.SubirConteoInventario(conteoInventario);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> SubirConteoInventarioAsync(PruebasUnitarias.wcf.cls_Cabecera conteoInventario) {
            return base.Channel.SubirConteoInventarioAsync(conteoInventario);
        }
        
        public System.IO.Stream TraspasosFarmacia(string id_bodega) {
            return base.Channel.TraspasosFarmacia(id_bodega);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> TraspasosFarmaciaAsync(string id_bodega) {
            return base.Channel.TraspasosFarmaciaAsync(id_bodega);
        }
        
        public System.IO.Stream DetalleTraspasos(string traspaso, string bodegaOrg) {
            return base.Channel.DetalleTraspasos(traspaso, bodegaOrg);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DetalleTraspasosAsync(string traspaso, string bodegaOrg) {
            return base.Channel.DetalleTraspasosAsync(traspaso, bodegaOrg);
        }
        
        public System.IO.Stream BuscarArticuloTraspaso(string id_bodega, string codigo) {
            return base.Channel.BuscarArticuloTraspaso(id_bodega, codigo);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> BuscarArticuloTraspasoAsync(string id_bodega, string codigo) {
            return base.Channel.BuscarArticuloTraspasoAsync(id_bodega, codigo);
        }
        
        public System.IO.Stream VerificarTraspasoKardexFarmacia(string id_bodega, string traspaso) {
            return base.Channel.VerificarTraspasoKardexFarmacia(id_bodega, traspaso);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> VerificarTraspasoKardexFarmaciaAsync(string id_bodega, string traspaso) {
            return base.Channel.VerificarTraspasoKardexFarmaciaAsync(id_bodega, traspaso);
        }
        
        public System.IO.Stream GenerarKardex(PruebasUnitarias.wcf.Traspaso traspaso) {
            return base.Channel.GenerarKardex(traspaso);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GenerarKardexAsync(PruebasUnitarias.wcf.Traspaso traspaso) {
            return base.Channel.GenerarKardexAsync(traspaso);
        }
        
        public System.IO.Stream ImagenArticulo(string codigo) {
            return base.Channel.ImagenArticulo(codigo);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ImagenArticuloAsync(string codigo) {
            return base.Channel.ImagenArticuloAsync(codigo);
        }
        
        public System.IO.Stream GuardarTemporal(PruebasUnitarias.wcf.Temporal temporal) {
            return base.Channel.GuardarTemporal(temporal);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GuardarTemporalAsync(PruebasUnitarias.wcf.Temporal temporal) {
            return base.Channel.GuardarTemporalAsync(temporal);
        }
        
        public System.IO.Stream RecuperarTemporal(string identificador) {
            return base.Channel.RecuperarTemporal(identificador);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> RecuperarTemporalAsync(string identificador) {
            return base.Channel.RecuperarTemporalAsync(identificador);
        }
        
        public System.IO.Stream EliminarTemporal(string identificador) {
            return base.Channel.EliminarTemporal(identificador);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> EliminarTemporalAsync(string identificador) {
            return base.Channel.EliminarTemporalAsync(identificador);
        }
        
        public System.IO.Stream Cookie(PruebasUnitarias.wcf.Cookie cookie1) {
            return base.Channel.Cookie(cookie1);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> CookieAsync(PruebasUnitarias.wcf.Cookie cookie) {
            return base.Channel.CookieAsync(cookie);
        }
        
        public System.IO.Stream Servidor(string ip) {
            return base.Channel.Servidor(ip);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ServidorAsync(string ip) {
            return base.Channel.ServidorAsync(ip);
        }
        
        public System.IO.Stream VerificarFactura(string serie) {
            return base.Channel.VerificarFactura(serie);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> VerificarFacturaAsync(string serie) {
            return base.Channel.VerificarFacturaAsync(serie);
        }
        
        public System.IO.Stream Digitalizacion() {
            return base.Channel.Digitalizacion();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DigitalizacionAsync() {
            return base.Channel.DigitalizacionAsync();
        }
        
        public System.IO.Stream VerificacionCajas(string bodega) {
            return base.Channel.VerificacionCajas(bodega);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> VerificacionCajasAsync(string bodega) {
            return base.Channel.VerificacionCajasAsync(bodega);
        }
        
        public System.IO.Stream GuardarPendientesVerificacion(System.Collections.Generic.List<PruebasUnitarias.wcf.TraspasoModel> traspasosModel) {
            return base.Channel.GuardarPendientesVerificacion(traspasosModel);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GuardarPendientesVerificacionAsync(System.Collections.Generic.List<PruebasUnitarias.wcf.TraspasoModel> traspasosModel) {
            return base.Channel.GuardarPendientesVerificacionAsync(traspasosModel);
        }
    }
}
